# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlackHack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlackHack

  pod 'InteractiveSideMenu'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'


  # add pods for any other desired Firebase products



# https://firebase.google.com/docs/ios/setup#available-pods

end
